version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@popperjs/core"
    versions:
    - 2.7.0
    - 2.8.2
    - 2.8.3
    - 2.8.4
    - 2.8.6
